/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eroscoin;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Singh
 */
public class Drecharge extends javax.swing.JFrame {

    /**
     * Creates new form Drecharge
     */
    public Drecharge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        vcno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        cno = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        poption = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        operator = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(430, 0, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/eros logo2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 410, 80);

        jPanel1.setBackground(new Color(211, 211, 211, 150));
        jPanel1.setLayout(null);

        jLabel3.setBackground(new Color(211, 211, 211, 150));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 50, 50, 40);

        uid.setEditable(false);
        uid.setBackground(new java.awt.Color(204, 204, 204));
        uid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uid.setForeground(new java.awt.Color(102, 0, 102));
        uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(uid);
        uid.setBounds(50, 90, 160, 40);

        jLabel5.setBackground(new Color(211, 211, 211, 150));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DTH Recharge");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 0, 150, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("NEXT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 530, 80, 30);

        jLabel4.setBackground(new Color(211, 211, 211, 150));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Viewing Card Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 200, 140, 40);

        vcno.setBackground(new java.awt.Color(204, 204, 204));
        vcno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        vcno.setForeground(new java.awt.Color(102, 0, 102));
        vcno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        vcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vcnoKeyTyped(evt);
            }
        });
        jPanel1.add(vcno);
        vcno.setBounds(50, 240, 160, 40);

        jLabel6.setBackground(new Color(211, 211, 211, 150));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Payment Option");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 280, 110, 40);

        card.setBackground(new Color(211, 211, 211, 150));
        card.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        card.setForeground(new java.awt.Color(255, 255, 255));
        card.setText("Card Number");
        jPanel1.add(card);
        card.setBounds(50, 350, 150, 40);

        cno.setBackground(new java.awt.Color(204, 204, 204));
        cno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cno.setForeground(new java.awt.Color(102, 0, 102));
        cno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnoKeyTyped(evt);
            }
        });
        jPanel1.add(cno);
        cno.setBounds(50, 390, 160, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("BACK");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 530, 80, 30);

        jLabel9.setBackground(new Color(211, 211, 211, 150));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Amount");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 430, 100, 40);

        amt.setBackground(new java.awt.Color(204, 204, 204));
        amt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        amt.setForeground(new java.awt.Color(102, 0, 102));
        amt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amtKeyTyped(evt);
            }
        });
        jPanel1.add(amt);
        amt.setBounds(50, 470, 160, 40);

        poption.setBackground(new java.awt.Color(204, 204, 204));
        poption.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        poption.setForeground(new java.awt.Color(102, 0, 102));
        poption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit Card", "Credit Card" }));
        poption.setSelectedIndex(-1);
        poption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poptionActionPerformed(evt);
            }
        });
        jPanel1.add(poption);
        poption.setBounds(50, 320, 150, 30);

        jLabel7.setBackground(new Color(211, 211, 211, 150));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Operator");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 130, 100, 40);

        operator.setBackground(new java.awt.Color(204, 204, 204));
        operator.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        operator.setForeground(new java.awt.Color(102, 0, 102));
        operator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dish TV", "Tata Sky", "Reliance Big TV", "Videocon D2H", "Sun Direct", "Airtel DTH" }));
        operator.setSelectedIndex(-1);
        operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorActionPerformed(evt);
            }
        });
        jPanel1.add(operator);
        operator.setBounds(50, 170, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 130, 270, 590);

        jLabel10.setBackground(new Color(211, 211, 211, 150));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("© 2017 EROSCOIN. All rights reserved");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 720, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/Home page Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 870);

        setSize(new java.awt.Dimension(481, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String u=uid.getText();
        String o=(String) operator.getSelectedItem();
        String vc=vcno.getText();
        String po=(String) poption.getSelectedItem();
        String cn=cno.getText();
        String am=amt.getText();
        msg ms=new msg();
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/eroscoin?zeroDateTimeBehavior=convertToNull", "root", "1234");
            Statement stmt=con.createStatement();
            String qq="insert into drecharge values('"+u+"', '"+o+"', '"+vc+"', '"+po+"', '"+cn+"', '"+am+"')";
            stmt.executeUpdate(qq);
            Home h=new Home();
            h.setVisible(true);
            h.userid.setVisible(false);
            h.userid.setText(u);
            ms.setVisible(true);
            ms.jLabel1.setText("DTH Has Been");
            ms.jLabel2.setText("Recharged Successfully");
            this.dispose();

        }
        catch(Exception ex)
        {
            ms.setVisible(true);
            ms.jLabel1.setText(ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vcnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcnoKeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vcnoKeyTyped

    private void cnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnoKeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cnoKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home h=new Home();
        h.setVisible(true);
        h.userid.setVisible(false);
        h.userid.setText(uid.getText());
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amtKeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_amtKeyTyped

    private void poptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poptionActionPerformed
        String c=(String)poption.getSelectedItem();
        card.setText(c+" Number");
        // TODO add your handling code here:
    }//GEN-LAST:event_poptionActionPerformed

    private void operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drecharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JLabel card;
    private javax.swing.JButton close;
    private javax.swing.JTextField cno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> operator;
    private javax.swing.JComboBox<String> poption;
    public javax.swing.JTextField uid;
    private javax.swing.JTextField vcno;
    // End of variables declaration//GEN-END:variables
}
