/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eroscoin;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author bscbp
 */
public class Mtransfer extends javax.swing.JFrame {

    /**
     * Creates new form Mtransfer
     */
    public Mtransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sacctno = new javax.swing.JTextField();
        racctno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rifsc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sifsc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(430, 0, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/eros logo2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 410, 80);

        jPanel1.setBackground(new Color(211, 211, 211, 150));
        jPanel1.setLayout(null);

        jLabel3.setBackground(new Color(211, 211, 211, 150));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 50, 50, 40);

        uid.setEditable(false);
        uid.setBackground(new java.awt.Color(204, 204, 204));
        uid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uid.setForeground(new java.awt.Color(102, 0, 102));
        uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(uid);
        uid.setBounds(50, 90, 270, 40);

        jLabel5.setBackground(new Color(211, 211, 211, 150));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Money Transfer");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 0, 150, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("NEXT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 540, 80, 30);

        jLabel4.setBackground(new Color(211, 211, 211, 150));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senders Account Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 130, 170, 40);

        sacctno.setBackground(new java.awt.Color(204, 204, 204));
        sacctno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sacctno.setForeground(new java.awt.Color(102, 0, 102));
        sacctno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        sacctno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sacctnoKeyTyped(evt);
            }
        });
        jPanel1.add(sacctno);
        sacctno.setBounds(50, 170, 270, 40);

        racctno.setBackground(new java.awt.Color(204, 204, 204));
        racctno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        racctno.setForeground(new java.awt.Color(102, 0, 102));
        racctno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        racctno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                racctnoKeyTyped(evt);
            }
        });
        jPanel1.add(racctno);
        racctno.setBounds(50, 330, 270, 40);

        jLabel8.setBackground(new Color(211, 211, 211, 150));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Recievers IFSC Code");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 370, 160, 40);

        rifsc.setBackground(new java.awt.Color(204, 204, 204));
        rifsc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rifsc.setForeground(new java.awt.Color(102, 0, 102));
        rifsc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        rifsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rifscKeyTyped(evt);
            }
        });
        jPanel1.add(rifsc);
        rifsc.setBounds(50, 410, 270, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("BACK");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 540, 80, 30);

        jLabel9.setBackground(new Color(211, 211, 211, 150));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reciever Account Number");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 290, 170, 40);

        jLabel11.setBackground(new Color(211, 211, 211, 150));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Senders IFSC Code");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 210, 170, 40);

        sifsc.setBackground(new java.awt.Color(204, 204, 204));
        sifsc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sifsc.setForeground(new java.awt.Color(102, 0, 102));
        sifsc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        sifsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sifscKeyTyped(evt);
            }
        });
        jPanel1.add(sifsc);
        sifsc.setBounds(50, 250, 270, 40);

        jLabel12.setBackground(new Color(211, 211, 211, 150));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Amount");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 450, 160, 40);

        amt.setBackground(new java.awt.Color(204, 204, 204));
        amt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        amt.setForeground(new java.awt.Color(102, 0, 102));
        amt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amtKeyTyped(evt);
            }
        });
        jPanel1.add(amt);
        amt.setBounds(50, 490, 270, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 130, 360, 590);

        jLabel10.setBackground(new Color(211, 211, 211, 150));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("© 2017 EROSCOIN. All rights reserved");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 720, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/Home page Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 870);

        setSize(new java.awt.Dimension(481, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String u=uid.getText();
        String san=sacctno.getText();
        String sic=sifsc.getText();
        String ran=racctno.getText();
        String ric=rifsc.getText();
        String am=amt.getText();
        msg ms=new msg();
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/eroscoin?zeroDateTimeBehavior=convertToNull", "root", "1234");
            Statement stmt=con.createStatement();
            String qq="insert into mtransfer values('"+u+"', '"+san+"', '"+sic+"', '"+ran+"', '"+ric+"', '"+am+"')";
            stmt.executeUpdate(qq);
            Home h=new Home();
            h.setVisible(true);
            h.userid.setVisible(false);
            h.userid.setText(u);
            ms.setVisible(true);
            ms.jLabel1.setText("Money has been");
            ms.jLabel2.setText("Transfer Successfully");
            this.dispose();

        }
        catch(Exception ex)
        {
            ms.setVisible(true);
            ms.jLabel1.setText(ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sacctnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sacctnoKeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_sacctnoKeyTyped

    private void racctnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_racctnoKeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_racctnoKeyTyped

    private void rifscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rifscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rifscKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home h=new Home();
        h.setVisible(true);
        h.userid.setVisible(false);
        h.userid.setText(uid.getText());
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sifscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sifscKeyTyped

    private void amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amtKeyTyped
char kc=evt.getKeyChar();
        if(!((kc>='0' && kc<='9') || kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_amtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mtransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mtransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JButton close;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField racctno;
    private javax.swing.JTextField rifsc;
    private javax.swing.JTextField sacctno;
    private javax.swing.JTextField sifsc;
    public javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
