/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eroscoin;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author bscbp
 */
public class Rpasswd2 extends javax.swing.JFrame {

    /**
     * Creates new form Rpasswd2
     */
    public Rpasswd2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/eros logo2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 410, 80);

        close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(420, 0, 50, 30);

        jPanel1.setBackground(new Color(211, 211, 211, 150));
        jPanel1.setLayout(null);

        jLabel3.setBackground(new Color(211, 211, 211, 150));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Question");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 90, 40);

        hq.setEditable(false);
        hq.setBackground(new java.awt.Color(204, 204, 204));
        hq.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hq.setForeground(new java.awt.Color(102, 0, 102));
        hq.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(hq);
        hq.setBounds(50, 170, 210, 40);

        jLabel5.setBackground(new Color(211, 211, 211, 150));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password Recovery");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 0, 180, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("NEXT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(100, 300, 80, 30);

        ha.setBackground(new java.awt.Color(204, 204, 204));
        ha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ha.setForeground(new java.awt.Color(102, 0, 102));
        ha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(ha);
        ha.setBounds(50, 250, 210, 40);

        jLabel4.setBackground(new Color(211, 211, 211, 150));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Answere");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 60, 40);

        uid.setEditable(false);
        uid.setBackground(new java.awt.Color(204, 204, 204));
        uid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uid.setForeground(new java.awt.Color(102, 0, 102));
        uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(uid);
        uid.setBounds(50, 90, 160, 40);

        jLabel6.setBackground(new Color(211, 211, 211, 150));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 50, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 130, 270, 380);

        jLabel10.setBackground(new Color(211, 211, 211, 150));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("© 2017 EROSCOIN. All rights reserved");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 510, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eroscoin/Home page Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 870);

        setSize(new java.awt.Dimension(464, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String u=uid.getText();
String an=ha.getText();
msg ms=new msg();
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/eroscoin?zeroDateTimeBehavior=convertToNull", "root", "1234");
    Statement stmt=con.createStatement();
    String qq="select * from erosid where user_id='"+u+"'";
    ResultSet rs=stmt.executeQuery(qq);
    while(rs.next())
    {
        if(an.equalsIgnoreCase(rs.getString("Hint_Answere")))
        {
            ms.setVisible(true);
            ms.jLabel1.setText("Your Password is");
            ms.jLabel2.setText(rs.getString("password"));
            this.setVisible(false);
        }
        else
        {
            ms.setVisible(true);
            ms.jLabel1.setText("Your Answere is");
            ms.jLabel2.setText("Wrong"); 
        }            
    }
}
catch(Exception ex)
{
    ms.setVisible(true);
    ms.jLabel1.setText(ex.getMessage());
}    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rpasswd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rpasswd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rpasswd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rpasswd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rpasswd2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    public javax.swing.JTextField ha;
    public javax.swing.JTextField hq;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
